services:
  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-file_uploader}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    networks:
    - file_uploader_net
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  
  file_uploader:
    build: .
    image: local/file_uploader
    container_name: 'file_uploader'
    restart: always
    ports:
      - '8000:8000'
    env_file:
      - .env
    networks:
      - file_uploader_net
    volumes:
      - ${FILE_UPLOAD_PATH}:/uploads
    depends_on:
      - db

networks:
  file_uploader_net:
    driver: bridge
volumes:
  db:
    driver: local